import { fontImportUrl } from "./fonts.ts";
import type { DesignSystem } from "./types.ts";

// This module holds only the pure builders. The code that puts these artifacts
// on disk lives in export.ts, next to the other renderers, so there is exactly
// one place that maps a format to a filename. Keeping the dependency pointing
// one way (export.ts -> context.ts) avoids an import cycle.

const SCALE_NAMES = ["xs", "sm", "base", "lg", "xl", "2xl", "3xl", "4xl", "5xl"];
const SCALE_EXPS = [-1, -0.5, 0, 1, 2, 3, 5, 7, 9];

function rampTable(label: string, ramp: Record<string, string>): string {
  const cells = Object.entries(ramp)
    .map(([stop, hex]) => [`--color-${label}-${stop}`, hex])
    .map(([v, hex]) => `\`${v}\` | \`${hex}\` | ![${hex}](https://placehold.co/24x12/${hex.slice(1)}/${hex.slice(1)})`)
    .join("\n");
  return `### ${label}\n\n| Token | Hex |\n| --- | --- |\n${cells}`;
}

/**
 * Agent-readable design brief (DESIGN.md style). The point is adherence:
 * an LLM that reads this at session start has explicit rules plus every
 * token value, so it stops inventing raw hex values and ad-hoc type sizes.
 */
export function designBrief(ds: DesignSystem): string {
  const sem = (k: keyof DesignSystem["semantic"]) => {
    const v = ds.semantic[k];
    return typeof v === "string" ? v : v.light;
  };
  const gradLines = ds.gradients
    ? Object.entries(ds.gradients)
        .map(([name, value]) => `- \`--gradient-${name}\`: \`${value}\``)
        .join("\n")
    : "";
  return [
    `# ${ds.name} — design system`,
    "",
    `> Generated by [kernic](https://github.com/intentionaut/kernic) · vibe: **${ds.vibe}** · created ${ds.createdAt.slice(0, 10)}`,
    "> This file is the single source of truth for visual decisions in this project.",
    "",
    "## Rules for AI agents",
    "",
    "1. Use ONLY the tokens below. Never invent raw hex, rgb(), or named CSS colors.",
    "2. Page backgrounds use `--background`; cards/panels use `--surface`; body text uses `--text`; secondary text uses `--muted-text`; hairlines use `--border`.",
    "3. Primary actions use `--color-primary-600` (hover: `--color-primary-500`). Focus rings use `--ring`.",
    "4. Dark mode: swap semantic tokens for their `dark:` counterparts — do not darken colors by hand.",
    `5. Headings: "${ds.fonts.heading}" · Body: "${ds.fonts.body}" · Code: "${ds.fonts.mono}". No other families.`,
    `6. Type sizes come only from \`--text-*\` (ratio ${ds.typeScale.ratio}). Corner radii only from \`--radius-*\` (${ds.radius.style}).`,
    "7. Accent color is for highlights, badges, and secondary emphasis — never for large surfaces.",
    "",
    "## Semantic tokens",
    "",
    "| Token | Light | Dark |",
    "| --- | --- | --- |",
    ...(["background", "surface", "text", "mutedText", "border", "ring"] as const).map((k) => {
      const v = ds.semantic[k];
      return `| \`--${k === "mutedText" ? "muted-text" : k}\` | \`${typeof v === "string" ? v : v.light}\` | \`${typeof v === "string" ? v : v.dark}\` |`;
    }),
    "",
    "## Color ramps",
    "",
    rampTable("primary", ds.colors.primary),
    "",
    rampTable("accent", ds.colors.accent),
    "",
    rampTable("neutral", ds.colors.neutral),
    "",
    "## Typography",
    "",
    "| Token | Size |",
    "| --- | --- |",
    ...SCALE_NAMES.map((n, i) => {
      const rem = (ds.typeScale.baseRem * Math.pow(ds.typeScale.ratio, SCALE_EXPS[i])).toFixed(3);
      return `| \`--text-${n}\` | \`${rem}rem\` |`;
    }),
    "",
    "## Radius",
    "",
    `sm \`${ds.radius.sm}\` · md \`${ds.radius.md}\` · lg \`${ds.radius.lg}\` · xl \`${ds.radius.xl}\``,
    "",
    ...(gradLines ? ["## Gradients", "", gradLines, ""] : []),
    "## Fonts",
    "",
    ...[ds.fonts.heading, ds.fonts.body, ds.fonts.mono]
      .filter((f, i, arr) => arr.indexOf(f) === i)
      .map((f) => `@import url("${fontImportUrl(f)}");`),
    "",
    "## Regenerating exports",
    "",
    "```bash",
    `kernic export ${ds.name} -f tailwind > src/app.css   # Tailwind v4 @theme`,
    `kernic export ${ds.name} -f css >> styles/global.css # plain CSS variables`,
    "```",
    "",
  ].join("\n");
}

/**
 * The rule a user pastes into CLAUDE.md / AGENTS.md / .cursorrules so the agent
 * actually reads the system. Single source for this copy: `kernic context`
 * prints the lines, the MCP apply_to_project tool returns the one-liner, and
 * neither can drift away from the other.
 */
export function agentRuleLines(ds: DesignSystem, briefPath = "./design.md"): string[] {
  return [
    `Visual design: follow ${briefPath} exactly (${ds.name}, vibe: ${ds.vibe}).`,
    "Use only its color, type, and radius tokens — never invent raw hex values.",
  ];
}

/** The same rule as one pasteable line. */
export function agentRule(ds: DesignSystem, briefPath = "./design.md"): string {
  return agentRuleLines(ds, briefPath).join(" ");
}

/** W3C Design Tokens (DTCG-style, stable 2025.10 semantics): $type/$value groups. */
export function dtcgTokens(ds: DesignSystem): string {
  const colorToken = (hex: string) => ({ $type: "color", $value: hex });
  const group: Record<string, unknown> = {};
  for (const [rampName, ramp] of Object.entries(ds.colors) as [string, Record<string, string>][]) {
    group[rampName] = Object.fromEntries(
      (Object.entries(ramp) as [string, string][]).map(([stop, hex]) => [stop, colorToken(hex)])
    );
  }
  const semGroup = (mode: "light" | "dark") =>
    Object.fromEntries(
      (["background", "surface", "text", "mutedText", "border", "ring"] as const).map((k) => [
        k === "mutedText" ? "muted-text" : k,
        colorToken(typeof ds.semantic[k] === "string" ? (ds.semantic[k] as string) : (ds.semantic[k] as any)[mode]),
      ])
    );
  group.semantic = { light: semGroup("light"), dark: semGroup("dark") };
  if (ds.gradients) {
    for (const [name, value] of Object.entries(ds.gradients)) {
      (group as any)[`gradient-${name}`] = { $type: "unknown", $value: value, $extensions: { "com.kernic.cssValue": value } };
    }
  }
  return JSON.stringify(
    {
      color: group,
      font: {
        heading: { $type: "fontFamily", $value: [ds.fonts.heading] },
        body: { $type: "fontFamily", $value: [ds.fonts.body] },
        mono: { $type: "fontFamily", $value: [ds.fonts.mono] },
      },
      radius: Object.fromEntries(
        (["sm", "md", "lg", "xl"] as const).map((k) => [k, { $type: "dimension", $value: ds.radius[k] }])
      ),
      typography: Object.fromEntries(
        SCALE_NAMES.map((n, i) => [
          n,
          {
            $type: "dimension",
            $value: `${(ds.typeScale.baseRem * Math.pow(ds.typeScale.ratio, SCALE_EXPS[i])).toFixed(3)}rem`,
          },
        ])
      ),
      $extensions: {
        "com.kernic": { name: ds.name, vibe: ds.vibe, schemaVersion: ds.schemaVersion },
      },
    },
    null,
    2
  ) + "\n";
}
