import { oklchComponents } from "./color.ts";
import { fontImportUrl } from "./fonts.ts";
import { findRampStop, semanticEntries } from "./semantic.ts";
import { SPACING_STEPS, easeCss, shadowCss, spacingKey } from "./tokens.ts";
import { SHADOW_LEVELS, TYPE_STEPS, type DesignSystem, type Ramp, type ShadowLayer, type TypeStep } from "./types.ts";
import { getVibe } from "./vibes.ts";
import { toYaml, type YamlValue } from "./yaml.ts";

// This module holds only the pure builders. The code that puts these artifacts
// on disk lives in export.ts, next to the other renderers, so there is exactly
// one place that maps a format to a filename. Keeping the dependency pointing
// one way (export.ts -> context.ts) avoids an import cycle.

/**
 * The DESIGN.md format version kernic writes. Google's spec is at `alpha` and
 * says to expect changes; pinning it here means a change shows up as a failing
 * conformance test rather than as files that drift.
 */
export const DESIGN_MD_SPEC = "alpha";
export const DESIGN_MD_FILE = "DESIGN.md";
/** The name kernic wrote before 0.2.0. Still recognised, still regenerated. */
export const LEGACY_BRIEF_FILE = "design.md";
export const KERNIC_URL = "https://github.com/intentionaut/kernic";
/** The substring every kernic brief carries, so a later run knows it may replace the file. */
export const OWNERSHIP_MARK = "Generated by [kernic]";

export { SPACING_STEPS, spacingKey };

/* ─────────────────────────── shared scales ─────────────────────────── */

/** Exponent on the ratio for each named step of the type scale. */
const TYPE_EXPONENTS: Record<TypeStep, number> = {
  xs: -1,
  sm: -0.5,
  base: 0,
  lg: 1,
  xl: 2,
  "2xl": 3,
  "3xl": 5,
  "4xl": 7,
  "5xl": 9,
};

export function typeSizeRem(ds: DesignSystem, exponent: number): string {
  return (ds.typeScale.baseRem * Math.pow(ds.typeScale.ratio, exponent)).toFixed(3);
}

/** `[name, rem]` for every step, the values every export prints. */
export function typeScaleEntries(ds: DesignSystem): Array<[TypeStep, string]> {
  return TYPE_STEPS.map((name) => [name, typeSizeRem(ds, TYPE_EXPONENTS[name])]);
}

/**
 * Typography roles for DESIGN.md. Each maps a job onto a step of the scale,
 * one of the three families, a weight and a tracking value from the system's
 * own typography tokens.
 */
const TYPE_ROLES = [
  { name: "display", step: "5xl", font: "heading", weight: "bold", tracking: "tight" },
  { name: "heading", step: "3xl", font: "heading", weight: "bold", tracking: "tight" },
  { name: "subheading", step: "xl", font: "heading", weight: "semibold", tracking: "normal" },
  { name: "body", step: "base", font: "body", weight: "regular", tracking: "normal" },
  { name: "small", step: "sm", font: "body", weight: "regular", tracking: "normal" },
  { name: "label", step: "xs", font: "body", weight: "medium", tracking: "wide" },
  { name: "code", step: "sm", font: "mono", weight: "regular", tracking: "normal" },
] as const;

/* ─────────────────────────── DESIGN.md ─────────────────────────── */

function vibeDescription(ds: DesignSystem): string {
  return getVibe(ds.vibe)?.description ?? `A kernic design system (vibe: ${ds.vibe}).`;
}

/** `{colors.primary-600}` when a hex sits on a ramp, else the hex itself. */
function colorRef(ds: DesignSystem, hex: string): string {
  const at = findRampStop(ds, hex);
  return at ? `{colors.${at.ramp}-${at.stop}}` : hex;
}

/** The machine-readable half of DESIGN.md, in the shape Google's spec defines. */
export function designFrontmatter(ds: DesignSystem): { [key: string]: YamlValue } {
  const colors: { [key: string]: string } = {};
  for (const [ramp, stops] of Object.entries(ds.colors) as [string, Ramp][]) {
    for (const [stop, hex] of Object.entries(stops)) colors[`${ramp}-${stop}`] = hex;
  }
  for (const entry of semanticEntries(ds)) {
    colors[entry.css] = colorRef(ds, entry.light);
    if (entry.dark !== entry.light) colors[`${entry.css}-dark`] = colorRef(ds, entry.dark);
  }
  colors.primary = "{colors.primary-600}";
  colors["primary-hover"] = "{colors.primary-500}";
  colors.accent = "{colors.accent-500}";

  const sizes = Object.fromEntries(typeScaleEntries(ds)) as Record<TypeStep, string>;
  const typography: { [key: string]: YamlValue } = {};
  for (const role of TYPE_ROLES) {
    typography[role.name] = {
      fontFamily: ds.fonts[role.font],
      fontSize: `${sizes[role.step]}rem`,
      fontWeight: ds.typography.weights[role.weight],
      lineHeight: ds.typography.leading[role.step],
      letterSpacing: ds.typography.tracking[role.tracking],
    };
  }

  const spacing: { [key: string]: string } = { unit: ds.spacing.unit, base: "1rem", ...ds.spacing.scale };

  return {
    version: DESIGN_MD_SPEC,
    name: ds.name,
    description: vibeDescription(ds),
    omitted: [{ section: "components", reason: "Component contracts arrive in a later kernic release." }],
    colors,
    typography,
    rounded: { sm: ds.radius.sm, md: ds.radius.md, lg: ds.radius.lg, xl: ds.radius.xl, DEFAULT: ds.radius.md, full: "9999px" },
    spacing,
  };
}

function rampTable(label: string, ramp: Record<string, string>): string {
  const cells = Object.entries(ramp)
    .map(([stop, hex]) => [`--color-${label}-${stop}`, hex])
    .map(([v, hex]) => `| \`${v}\` | \`${hex}\` | ![${hex}](https://placehold.co/24x12/${hex.slice(1)}/${hex.slice(1)}) |`)
    .join("\n");
  return `### ${label[0].toUpperCase()}${label.slice(1)} ramp\n\n| Token | Hex | |\n| --- | --- | --- |\n${cells}`;
}

const ROLE_NOTES: Record<string, string> = {
  background: "page background",
  surface: "cards, panels, inputs",
  text: "body copy and headings",
  "muted-text": "secondary text, captions, placeholders",
  border: "hairlines and dividers",
  ring: "focus rings",
};

const SHADOW_NOTES: Record<(typeof SHADOW_LEVELS)[number], string> = {
  xs: "inputs and small controls at rest",
  sm: "cards at rest",
  md: "cards on hover, dropdowns",
  lg: "popovers, floating panels",
  xl: "dialogs and sheets",
};

/**
 * DESIGN.md: YAML front matter carrying every token, then prose in the section
 * order Google's spec defines, ending with the rules an agent must follow. The
 * front matter is the normative part; the prose says how to apply it.
 */
export function designBrief(ds: DesignSystem): string {
  const fonts = [ds.fonts.heading, ds.fonts.body, ds.fonts.mono].filter((f, i, arr) => arr.indexOf(f) === i);
  const roleLines = semanticEntries(ds).map((e) => {
    const dark = e.dark !== e.light ? ` (dark \`${e.dark}\`)` : "";
    const label = e.css === "muted-text" ? "Muted text" : e.css[0].toUpperCase() + e.css.slice(1);
    return `- **${label}** \`--${e.css}\` \`${e.light}\`${dark}: ${ROLE_NOTES[e.css]}.`;
  });
  const gradientLines = Object.entries(ds.gradients ?? {}).map(([name, value]) => `- \`--gradient-${name}\`: \`${value}\``);
  const t = ds.typography;
  const m = ds.motion;

  const frontmatter = toYaml(designFrontmatter(ds));
  // The ownership comment sits on line 2 so it is inside the first 512 bytes
  // whatever the token count, which is where isKernicOwned looks for it.
  const head = `---\n# ${OWNERSHIP_MARK}(${KERNIC_URL}) · vibe: ${ds.vibe} · created ${ds.createdAt.slice(0, 10)}\n${frontmatter}---\n`;

  return [
    head,
    "## Overview",
    "",
    `${vibeDescription(ds)} This is the "${ds.name}" design system, and this file is the single source of truth for visual decisions in the project. The front matter holds the tokens and is the normative part; the sections below say how to apply them.`,
    "",
    `Written by kernic to the DESIGN.md \`${DESIGN_MD_SPEC}\` spec. Regenerate it, and the token files beside it, with \`kernic context ${ds.name}\`.`,
    "",
    "## Colors",
    "",
    "Roles, with the light value first:",
    "",
    ...roleLines,
    "- **Primary** `--color-primary-600` (hover `--color-primary-500`): buttons, links, the one action on a screen.",
    "- **Accent** `--color-accent-500`: highlights, badges, secondary emphasis. Never a large surface.",
    "",
    "Dark mode swaps every role for its dark value. Nothing gets darkened by hand.",
    "",
    rampTable("primary", ds.colors.primary),
    "",
    rampTable("accent", ds.colors.accent),
    "",
    rampTable("neutral", ds.colors.neutral),
    "",
    ...(gradientLines.length > 0 ? ["### Gradients", "", ...gradientLines, ""] : []),
    "## Typography",
    "",
    `- Headings: "${ds.fonts.heading}"`,
    `- Body: "${ds.fonts.body}"`,
    `- Code: "${ds.fonts.mono}"`,
    "",
    `No other families. Sizes come from a ${ds.typeScale.ratio} scale on ${ds.typeScale.baseRem}rem; the roles in the front matter (display, heading, subheading, body, small, label, code) sit on these steps, each with its line height.`,
    "",
    "| Token | Size | Line height |",
    "| --- | --- | --- |",
    ...typeScaleEntries(ds).map(([name, rem]) => `| \`--text-${name}\` | \`${rem}rem\` | \`${t.leading[name]}\` |`),
    "",
    `Weights: regular ${t.weights.regular}, medium ${t.weights.medium}, semibold ${t.weights.semibold}, bold ${t.weights.bold} (\`--font-weight-*\`). Tracking: tight \`${t.tracking.tight}\` for display and headings, normal \`${t.tracking.normal}\` for body, wide \`${t.tracking.wide}\` for labels and small caps (\`--tracking-*\`).`,
    "",
    "Load the fonts with:",
    "",
    "```css",
    ...fonts.map((f) => `@import url("${fontImportUrl(f)}");`),
    "```",
    "",
    "## Layout",
    "",
    "### Spacing",
    "",
    `The unit is \`${ds.spacing.unit}\` (\`--spacing\`). Named steps are \`--space-*\`, in rem: ${SPACING_STEPS.join(", ")}. Padding, gaps and margins come from this scale and nothing off it.`,
    "",
    "### Breakpoints and containers",
    "",
    `Breakpoints (\`--breakpoint-*\`): sm ${ds.breakpoints.sm}, md ${ds.breakpoints.md}, lg ${ds.breakpoints.lg}, xl ${ds.breakpoints.xl}, 2xl ${ds.breakpoints["2xl"]}. Containers (\`--container-*\`): sm ${ds.containers.sm}, md ${ds.containers.md}, lg ${ds.containers.lg}, xl ${ds.containers.xl}. Prose measures \`${ds.containers.measure}\` (\`--measure\`).`,
    "",
    "### Motion",
    "",
    `Transitions are ${m.preset}: fast \`${m.duration.fast}\`, base \`${m.duration.base}\`, slow \`${m.duration.slow}\` (\`--duration-*\`). Easing: out \`${easeCss(m.ease.out)}\` for things arriving, in-out \`${easeCss(m.ease.inOut)}\` for things moving, emphasized \`${easeCss(m.ease.emphasized)}\` for the one moment that deserves it (\`--ease-*\`). No overshoot on state changes. Respect \`prefers-reduced-motion\` by dropping the transition, not the state.`,
    "",
    "## Elevation & Depth",
    "",
    "Layers are separated first by color: `--surface` sits on `--background`, and `--border` draws the hairline between them. Shadows add depth on top and are tinted from the neutral ramp, so they belong to the palette. Each has a light and a dark value; dark mode uses the denser set.",
    "",
    ...SHADOW_LEVELS.map((level) => `- \`--shadow-${level}\`: ${SHADOW_NOTES[level]}. Light \`${shadowCss(ds.shadows[level].light)}\`.`),
    "",
    "## Shapes",
    "",
    `Corners are ${ds.radius.style}: \`--radius-sm\` ${ds.radius.sm}, \`--radius-md\` ${ds.radius.md} (the default), \`--radius-lg\` ${ds.radius.lg}, \`--radius-xl\` ${ds.radius.xl}. \`rounded.full\` (9999px) is for pills and avatars only.`,
    "",
    "## Do's and Don'ts",
    "",
    "### Do",
    "",
    "- Use only the tokens in this file, by their CSS variable names.",
    "- Put page backgrounds on `--background`, cards and panels on `--surface`, body text in `--text`, secondary text in `--muted-text`, hairlines in `--border`.",
    "- Use `--color-primary-600` for primary actions, `--color-primary-500` on hover, and `--ring` for focus rings.",
    `- Set headings in "${ds.fonts.heading}", body in "${ds.fonts.body}", code in "${ds.fonts.mono}".`,
    "- Take type sizes from `--text-*`, weights from `--font-weight-*`, corner radii from `--radius-*`, spacing from `--space-*`, shadows from `--shadow-*`.",
    "- Animate with `--duration-*` and `--ease-*`, and turn transitions off under `prefers-reduced-motion`.",
    "- Switch to the dark values of the semantic tokens and shadows in dark mode.",
    "",
    "### Don't",
    "",
    "- Invent raw hex, `rgb()` or named CSS colors.",
    "- Use any font family other than the three above.",
    "- Darken or lighten a color by hand for dark mode.",
    "- Put the accent color on a large surface; it is for highlights, badges and secondary emphasis.",
    "- Use a type size, radius, spacing, shadow or duration that is not a token.",
    "- Use `transition: all`, or an easing that overshoots, on a state change.",
    "",
  ].join("\n");
}

/** The `##` headings DESIGN.md carries, in spec order. Components is declared omitted for now. */
export const DESIGN_MD_HEADINGS = [
  "## Overview",
  "## Colors",
  "## Typography",
  "## Layout",
  "## Elevation & Depth",
  "## Shapes",
  "## Do's and Don'ts",
] as const;

/**
 * The rule a user pastes into CLAUDE.md / AGENTS.md / .cursorrules so the agent
 * actually reads the system. Single source for this copy: `kernic context`
 * prints the lines, the MCP apply_to_project tool returns the one-liner, and
 * neither can drift away from the other.
 */
export function agentRuleLines(ds: DesignSystem, briefPath = `./${DESIGN_MD_FILE}`): string[] {
  return [
    `Visual design: follow ${briefPath} exactly (${ds.name}, vibe: ${ds.vibe}).`,
    "Use only its color, type, and radius tokens — never invent raw hex values.",
  ];
}

/** The same rule as one pasteable line. */
export function agentRule(ds: DesignSystem, briefPath = `./${DESIGN_MD_FILE}`): string {
  return agentRuleLines(ds, briefPath).join(" ");
}

/* ─────────────────────────── DTCG 2025.10 ─────────────────────────── */

/** A colour value: OKLCH components, plus the hex every older pipeline and Figma read. */
function colorValue(hex: string, alpha?: number) {
  return { colorSpace: "oklch", components: oklchComponents(hex), ...(alpha === undefined ? {} : { alpha }), hex };
}

function dtcgColor(hex: string) {
  return { $type: "color", $value: colorValue(hex) };
}

/** An alias to another token, `{group.token}` form. */
function dtcgAlias(type: string, path: string) {
  return { $type: type, $value: `{${path}}` };
}

/** `"0.25rem"` → `{ value: 0.25, unit: "rem" }`, the 2025.10 dimension shape. */
export function dtcgDimension(dimension: string) {
  const m = /^(-?\d*\.?\d+)(px|rem|em)$/.exec(dimension.trim());
  if (!m) throw new Error(`Not a dimension: "${dimension}". Expected a number with px, rem or em.`);
  return { $type: "dimension", $value: { value: Number(m[1]), unit: m[2] } };
}

/** `"200ms"` → `{ value: 200, unit: "ms" }`. */
export function dtcgDuration(duration: string) {
  const m = /^(\d*\.?\d+)(ms|s)$/.exec(duration.trim());
  if (!m) throw new Error(`Not a duration: "${duration}". Expected a number with ms or s.`);
  return { $type: "duration", $value: { value: Number(m[1]), unit: m[2] } };
}

function dtcgShadow(layers: ShadowLayer[]) {
  return {
    $type: "shadow",
    $value: layers.map((l) => ({
      color: colorValue(l.color, l.alpha),
      offsetX: dtcgDimension(l.x).$value,
      offsetY: dtcgDimension(l.y).$value,
      blur: dtcgDimension(l.blur).$value,
      spread: dtcgDimension(l.spread).$value,
    })),
  };
}

/**
 * W3C Design Tokens, Format Module 2025.10: colours as OKLCH objects with a
 * hex fallback, dimensions as value + unit, semantic roles as references to
 * the ramp stop they were chosen from, shadows, durations and easing curves
 * as their own types, and typography roles as composites. Gradients are CSS
 * strings the format cannot express, so they travel in the `com.kernic`
 * extension, as does the prose measure (`ch` is not a format unit).
 */
export function dtcgTokens(ds: DesignSystem): string {
  const color: Record<string, unknown> = {};
  for (const [rampName, ramp] of Object.entries(ds.colors) as [string, Ramp][]) {
    color[rampName] = Object.fromEntries(Object.entries(ramp).map(([stop, hex]) => [stop, dtcgColor(hex)]));
  }
  const semantic = (mode: "light" | "dark") =>
    Object.fromEntries(
      semanticEntries(ds).map((e) => {
        const hex = e[mode];
        const at = findRampStop(ds, hex);
        return [e.css, at ? dtcgAlias("color", `color.${at.ramp}.${at.stop}`) : dtcgColor(hex)];
      })
    );
  color.semantic = { light: semantic("light"), dark: semantic("dark") };

  const t = ds.typography;
  const sizes = Object.fromEntries(typeScaleEntries(ds)) as Record<TypeStep, string>;
  const roles = Object.fromEntries(
    TYPE_ROLES.map((role) => [
      role.name,
      {
        $type: "typography",
        $value: {
          fontFamily: `{font.${role.font}}`,
          fontSize: `{typography.size.${role.step}}`,
          fontWeight: `{typography.weight.${role.weight}}`,
          letterSpacing: `{typography.tracking.${role.tracking}}`,
          lineHeight: `{typography.leading.${role.step}}`,
        },
      },
    ])
  );

  const extension: Record<string, unknown> = {
    generator: "kernic",
    name: ds.name,
    vibe: ds.vibe,
    schemaVersion: ds.schemaVersion,
    format: "2025.10",
    measure: ds.containers.measure,
  };
  if (ds.gradients && Object.keys(ds.gradients).length > 0) extension.gradients = ds.gradients;

  return (
    JSON.stringify(
      {
        color,
        font: {
          heading: { $type: "fontFamily", $value: [ds.fonts.heading] },
          body: { $type: "fontFamily", $value: [ds.fonts.body] },
          mono: { $type: "fontFamily", $value: [ds.fonts.mono] },
        },
        radius: Object.fromEntries((["sm", "md", "lg", "xl"] as const).map((k) => [k, dtcgDimension(ds.radius[k])])),
        typography: {
          size: Object.fromEntries(typeScaleEntries(ds).map(([name, rem]) => [name, dtcgDimension(`${rem}rem`)])),
          leading: Object.fromEntries(TYPE_STEPS.map((s) => [s, { $type: "number", $value: t.leading[s] }])),
          weight: Object.fromEntries(Object.entries(t.weights).map(([k, v]) => [k, { $type: "fontWeight", $value: v }])),
          tracking: Object.fromEntries(Object.entries(t.tracking).map(([k, v]) => [k, dtcgDimension(v)])),
          ...roles,
        },
        spacing: {
          unit: dtcgDimension(ds.spacing.unit),
          ...Object.fromEntries(Object.entries(ds.spacing.scale).map(([k, v]) => [k, dtcgDimension(v)])),
        },
        shadow: {
          light: Object.fromEntries(SHADOW_LEVELS.map((l) => [l, dtcgShadow(ds.shadows[l].light)])),
          dark: Object.fromEntries(SHADOW_LEVELS.map((l) => [l, dtcgShadow(ds.shadows[l].dark)])),
        },
        motion: {
          duration: Object.fromEntries(Object.entries(ds.motion.duration).map(([k, v]) => [k, dtcgDuration(v)])),
          ease: Object.fromEntries(Object.entries(ds.motion.ease).map(([k, v]) => [k, { $type: "cubicBezier", $value: v }])),
        },
        breakpoint: Object.fromEntries(Object.entries(ds.breakpoints).map(([k, v]) => [k, dtcgDimension(v)])),
        container: Object.fromEntries(
          Object.entries(ds.containers)
            .filter(([k]) => k !== "measure")
            .map(([k, v]) => [k, dtcgDimension(v)])
        ),
        $extensions: { "com.kernic": extension },
      },
      null,
      2
    ) + "\n"
  );
}
